# Generated by Django 4.2.2 on 2023-08-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_essay_topic_delete_blog_essay_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('E', 'Essay'), ('RP', 'Research paper'), ('CW', 'Critical Writing'), ('R', 'Report'), ('AB', 'Annotated Bibliography'), ('A', 'Assessment'), ('S', 'Summarizing'), ('CW', 'Coursework'), ('D', 'Dissertation'), ('PR', 'Paraphrasing'), ('T', 'Thesis'), ('PO', 'Poster'), ('Q', 'Q&A'), ('BR', 'Book Review'), ('BL', 'Business Letter'), ('CS', 'Case Study'), ('EO', 'Extended Outline'), ('MR', 'Movie Review'), ('NP', 'Nursing Paper'), ('OT', 'Online Test'), ('TP', 'Term Paper'), ('RD', 'Reading Diary'), ('DBP', 'Discussion Board Post'), ('PPP', 'Power Point Presentation')], max_length=100)),
                ('study_level', models.CharField(choices=[('E', 'Essay'), ('RP', 'Research paper'), ('CW', 'Critical Writing'), ('R', 'Report'), ('AB', 'Annotated Bibliography'), ('A', 'Assessment'), ('S', 'Summarizing'), ('CW', 'Coursework'), ('D', 'Dissertation'), ('PR', 'Paraphrasing'), ('T', 'Thesis'), ('PO', 'Poster'), ('Q', 'Q&A'), ('BR', 'Book Review'), ('BL', 'Business Letter'), ('CS', 'Case Study'), ('EO', 'Extended Outline'), ('MR', 'Movie Review'), ('NP', 'Nursing Paper'), ('OT', 'Online Test'), ('TP', 'Term Paper'), ('RD', 'Reading Diary'), ('DBP', 'Discussion Board Post'), ('PPP', 'Power Point Presentation')], max_length=100)),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
