# Generated by Django 4.2.2 on 2023-08-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_helprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
