# Generated by Django 4.2.2 on 2023-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_paper_description_paper_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
