# Generated by Django 4.2.2 on 2023-08-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_paper_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='description',
        ),
    ]
