# Generated by Django 4.2.2 on 2023-08-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_paper_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='price',
        ),
        migrations.AddField(
            model_name='paper',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='topic',
            field=models.CharField(choices=[('E', 'Education'), ('D', 'Development'), ('L', 'Leadership'), ('R', 'Research'), ('H', 'History'), ('E', 'Economics'), ('B', 'Business'), ('S', 'Sports'), ('F', 'Farminig'), ('N', 'Nursing'), ('A', 'Accounting'), ('F', 'Finance'), ('M', 'Marketing'), ('C', 'Calculus'), ('P', 'Proposals'), ('PR', 'Proof reading'), ('BM', 'Business management'), ('HR', 'Human Resource'), ('SC', 'Supply chain & logistics'), ('TD', 'Thesis/Dissertations'), ('CP', 'Concept Papers'), ('BP', 'Business Plans'), ('SM', 'Strategic management'), ('DA', 'Data analysis'), ('AC', 'Academic Coaching/Online Tutor')], max_length=100),
        ),
    ]
