PAPER_TYPE = [
    ("E", "Essay"),
    ("RP", "Research paper"),
    ("CW", "Critical Writing"),
    ("R", "Report"),
    ("AB", "Annotated Bibliography"),
    ("A", "Assessment"),
    ("S", "Summarizing"),
    ("CW", "Coursework"),
    ("D", "Dissertation"),
    ("PR", "Paraphrasing"),
    ("T", "Thesis"),
    ("PO", "Poster"),
    ("Q", "Q&A"),
    ("BR", "Book Review"),
    ("BL", "Business Letter"),
    ("CS", "Case Study"),
    ("EO", "Extended Outline"),
    ("MR", "Movie Review"),
    ("NP", "Nursing Paper"),
    ("OT", "Online Test"),
    ("TP", "Term Paper"),
    ("RD", "Reading Diary"),
    ("DBP", "Discussion Board Post"),
    ("PPP", "Power Point Presentation"),
]

PAPER_TYPE_PRICING = {
    "E": 50,
    "RP": 100,
    "CW": 150,
    "R": 200,
    "AB": 250,
    "A": 300,
    "S": 350,
    "CW": 400,
    "D": 450,
    "PR": 500,
    "T": 550,
    "PO": 600,
    "Q": 650,
    "BR": 750,
    "BL": 800,
    "CS": 850,
    "EO": 900,
    "MR": 950,
    "NP": 1000,
    "OT": 1050,
    "TP": 1100,
    "RD": 1150,
    "DBP": 1200,
    "PPP": 1250,
}

STUDY_LEVEL = [
    ("S", "School"),
    ("C", "College"),
    ("B", "Bachelor"),
    ("M", "Masters"),
    ("P", "PhD"),
]

STUDY_LEVEL_PRICING = {
    "S": 20,
    "C": 30,
    "B": 40,
    "M": 50,
    "P": 60,
}

TOPICS = [
    ("E", "Education"),
    ("D", "Development"),
    ("L", "Leadership"),
    ("R", "Research"),
    ("H", "History"),
    ("E", "Economics"),
    ("B", "Business"),
    ("S", "Sports"),
    ("F", "Farminig"),
    ("N", "Nursing"),
    ("A", "Accounting"),
    ("F", "Finance"),
    ("M", "Marketing"),
    ("C", "Calculus"),
    ("P", "Proposals"),
    ("PR", "Proof reading"),
    ("BM", "Business management"),
    ("HR", "Human Resource"),
    ("SC", "Supply chain & logistics"),
    ("TS", "Thesis"),
    ("CP", "Concept Papers"),
    ("BP", "Business Plans"),
    ("SM", "Strategic management"),
    ("DA", "Data analysis"),
    ("OT", "Online Tutor"),
]


PRICE_PER_DAY = {
    "1": 50,
    "2": 40,
    "3": 35,
    "4": 30,
    "5": 25,
}
