# Generated by Django 4.2.2 on 2023-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_helprequest_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='helprequest',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
